version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  versioning-strategy: lockfile-only
  ignore:
  - dependency-name: cross-fetch
    versions:
    - 3.0.6
    - 3.1.0
    - 3.1.1
    - 3.1.2
    - 3.1.3
  - dependency-name: lodash
    versions:
    - 4.17.20
