language: node_js

node_js:
  - "8"

dist: trusty

sudo: required

install:
  - npm install
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter

script:
  - npm run lint
  - npm run test:travis

after_success:
  - npm run codecov

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT -t lcov
