name: CI

on:
  push:
    branches:
      - '**'
      - '!dependabot/**'

jobs:
  base-node-pipeline:
    uses: DEFRA/water-abstraction-orchestration/.github/workflows/base-node-pipeline.yml@develop
    with:
      serviceName: DEFRA_water-abstraction-ui
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 12.x, 14.x ]
    env:
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/permits
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of sonarcloud analysis
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: |
          REDIS_HOST=localhost REDIS_PORT=6379 npm run test:ci
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage/

  Code-Climate:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download artifacts
        uses: actions/download-artifact@v2
      - name: Upload to Code Climate
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageLocations: |
            ${{github.workspace}}/coverage/*.lcov:lcov

  Code-Cov:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download artifacts
        uses: actions/download-artifact@v2
      - name: Upload to Codecov
        uses: codecov/codecov-action@v2
        with:
          directory: ./coverage/
